export const state = {
  status: null,
  statusText: "",
  locale: "zh-CN",
  sessions: [],
  contacts: [],
  groupMembers: [],
  groupMemberByUserId: new Map(),
  groupNamePendingIds: new Set(),
  groupCardPendingKeys: new Set(),
  groupSpecialTitlePendingKeys: new Set(),
  activeSessionId: "",
  messagesBySession: new Map(),
  messageHistoryBySession: new Map(),
  sessionMutePendingIds: new Set(),
  sessionPinPendingIds: new Set(),
  sessionDeletePendingIds: new Set(),
  messageRecallPendingIds: new Set(),
  searchKeyword: "",
  leftListMode: "sessions",
  pendingUploads: [],
  sendQueue: [],
  sendQueueProcessing: false,
  sendQueueSequence: 0,
  optimisticPreviewUrlsByMessageId: new Map(),
  composerMentionActive: false,
  composerMentionQuery: "",
  composerMentionRange: null,
  composerMentionSuggestions: [],
  composerMentionActiveIndex: 0,
  composerSelectionRange: null,
  composerReplyTarget: null,
  emojiPanelOpen: false,
  qqFaceCache: new Map(),
  qqFaceCatalogReady: false,
  qqFaceCatalogLoading: false,
  qqFaceCatalogError: "",
  qqFaceCatalogIds: [],
  qqFacePanelLimit: 0,
  qqFaceMissingIds: new Set(),
  qqFacePendingIds: new Set(),
  forwardMessagesById: new Map(),
  forwardLoadingIds: new Set(),
  forwardErrorById: new Map(),
  forwardModalOpen: false,
  forwardModalStack: [],
  forwardModalFetchCount: 0,
  isRecording: false,
  recordingBusy: false,
  sseSubscriptionId: "",
  sseConnected: false,
  sseReconnectTimerId: 0,
  messageBounceOffset: 0,
  messageBounceTimerId: 0,
  messageWheelIdleTimerId: 0,
  messageTouchId: null,
  messageTouchLastY: 0,
  messagePrefetching: new Set(),
  messageListAtBottom: true,
  messageViewSyncKey: "",
  currentReadingMessageId: "",
  messageExitCursorBySession: new Map(),
  pendingNewMessageCount: 0,
  profileModalOpen: false,
  profileModalLoading: false,
  profileModalRefreshing: false,
  profileModalError: "",
  profileModalIdentity: null,
  profileModalUser: null,
  profileModalMember: null,
  activeProfileTarget: null,
};
