export const state = {
  status: null,
  statusText: "",
  locale: "zh-CN",
  sessions: [],
  contacts: [],
  groupMembers: [],
  activeSessionId: "",
  messagesBySession: new Map(),
  sessionMutePendingIds: new Set(),
  searchKeyword: "",
  showingContacts: false,
  pendingUploads: [],
  composerMentionActive: false,
  composerMentionQuery: "",
  composerMentionRange: null,
  composerMentionSuggestions: [],
  composerMentionActiveIndex: 0,
  composerSelectionRange: null,
  composerReplyTarget: null,
  emojiPanelOpen: false,
  qqFaceCache: new Map(),
  qqFaceCatalogReady: false,
  qqFaceCatalogLoading: false,
  qqFaceCatalogError: "",
  qqFaceCatalogIds: [],
  qqFacePanelLimit: 0,
  qqFaceMissingIds: new Set(),
  qqFacePendingIds: new Set(),
  isRecording: false,
  recordingBusy: false,
  sseSubscriptionId: "",
  sseConnected: false,
  sseReconnectTimerId: 0,
  messageBounceOffset: 0,
  messageBounceTimerId: 0,
  messageWheelIdleTimerId: 0,
  messageTouchId: null,
  messageTouchLastY: 0,
  messagePrefetching: new Set(),
  messageListAtBottom: true,
  messageViewSyncKey: "",
  currentReadingMessageId: "",
  messageExitCursorBySession: new Map(),
  pendingNewMessageCount: 0,
  profileModalOpen: false,
  profileModalLoading: false,
  profileModalRefreshing: false,
  profileModalError: "",
  profileModalIdentity: null,
  profileModalUser: null,
  profileModalMember: null,
  activeProfileTarget: null,
};
