export const els = {
  adapterDot: document.getElementById("adapterDot"),
  accountAvatar: document.getElementById("accountAvatar"),
  accountName: document.getElementById("accountName"),
  accountMeta: document.getElementById("accountMeta"),
  sessionSearchInput: document.getElementById("sessionSearchInput"),
  leftListTitle: document.getElementById("leftListTitle"),
  leftListCount: document.getElementById("leftListCount"),
  sessionList: document.getElementById("sessionList"),
  contactList: document.getElementById("contactList"),
  chatTitle: document.getElementById("chatTitle"),
  messageList: document.getElementById("messageList"),
  messageListContent: document.getElementById("messageListContent"),
  composerForm: document.getElementById("composerForm"),
  composerPreview: document.getElementById("composerPreview"),
  composerInput: document.getElementById("composerInput"),
  facePickerWrap: document.getElementById("facePickerWrap"),
  facePickerBtn: document.getElementById("facePickerBtn"),
  facePickerPanel: document.getElementById("facePickerPanel"),
  facePickerList: document.getElementById("facePickerList"),
  attachmentButton: document.getElementById("attachmentButton"),
  attachmentInput: document.getElementById("attachmentInput"),
  sendBtn: document.getElementById("sendBtn"),
  chatMenuBtn: document.getElementById("chatMenuBtn"),
  toggleContactsBtn: document.getElementById("toggleContactsBtn"),
  memberPanelTitle: document.getElementById("memberPanelTitle"),
  memberList: document.getElementById("memberList"),
  quoteModal: document.getElementById("quoteModal"),
  quoteModalBackdrop: document.getElementById("quoteModalBackdrop"),
  quoteModalTitle: document.getElementById("quoteModalTitle"),
  quoteModalMeta: document.getElementById("quoteModalMeta"),
  quoteModalBody: document.getElementById("quoteModalBody"),
  quoteModalCloseBtn: document.getElementById("quoteModalCloseBtn"),
};

export const MAX_ATTACHMENT_SIZE = 15 * 1024 * 1024;
export const bridge = window.AstrBotPluginPage;
