export const state = {
  status: null,
  locale: "zh-CN",
  sessions: [],
  contacts: [],
  members: [],
  activeSessionId: "",
  messagesBySession: new Map(),
  mediaObjectUrls: new Map(),
  mediaObjectUrlPending: new Map(),
  sessionKeyword: "",
  showContacts: false,
  faces: [],
  facePickerPinned: false,
  facePickerCloseTimerId: 0,
  warmedFaceKeys: new Set(),
  faceWarmupScheduled: false,
  faceWarmupPaused: false,
  pendingAttachments: [],
  pollTimerId: 0,
  messageBounceOffset: 0,
  messageBounceTimerId: 0,
  messageWheelIdleTimerId: 0,
  messageTouchId: null,
  messageTouchLastY: 0,
  messageHydrationTicket: 0,
  messagePrefetching: new Set(),
};
